version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-tryon-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Using environment variables from .env file
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - TRYON_API_KEY=${TRYON_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      # Add your ngrok authtoken if needed for webhooks
      # - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    restart: always
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
      - virtual_tryon_uploads:/app/static/uploads
      - virtual_tryon_logs:/app/static/logs
      - virtual_tryon_temp:/app/static/temp
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  virtual_tryon_uploads:
  virtual_tryon_logs:
  virtual_tryon_temp: 