version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-tryon-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLOUDINARY_CLOUD_NAME=dj3ewvbqm
      - CLOUDINARY_API_KEY=182963992493551
      - CLOUDINARY_API_SECRET=Jw9FTSGXX2VxuEaxKA-l8E2Kqag
      - ARTIFICIAL_STUDIO_API_KEY=dd240ad8f2e64de35e0b25ecddf1b42c2a7e637d
      # Add your ngrok authtoken if needed for webhooks
      # - NGROK_AUTHTOKEN=your_ngrok_auth_token
    restart: always
    volumes:
      - virtual_tryon_uploads:/app/uploads
      - virtual_tryon_logs:/app/logs
      - virtual_tryon_temp:/app/temp
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  virtual_tryon_uploads:
  virtual_tryon_logs:
  virtual_tryon_temp: 